house_information:
  favorites:
    - entity: binary_sensor.doorbell_button
      type: doorbell
      icon_on: mdi:bell
      icon_off: mdi:bell
    - entity: binary_sensor.hallway_door_contact
      type: door
      icon_on: mdi:door
      icon_off: mdi:door-open
    - entity: binary_sensor.garage_doorfront_contact
      type: door
      icon_on: mdi:garage-open
      icon_off: mdi:garage
    - entity: binary_sensor.washing_machine_running
      icon_on: mdi:dishwasher
      icon_off: mdi:dishwasher-off
    - entity: binary_sensor.dryer_machine_running
      icon_on: mdi:tumble-dryer
      icon_off: mdi:tumble-dryer-off
    - entity: input_select.zigbee2mqtt_log_level
    - entity: input_text.zigbee2mqtt_new_name

  calendar:
    - calendar.gft
    - calendar.oud_papier
    - calendar.pmd_afval
    - calendar.restafval

  addons:
    - name: Hello more page
      icon: fas:chart-area
      path: 'dwains-theme/addons/more_page/hello-more-page/page.yaml'
      data:
        some_data: 'This is some data parsed.'
        some_other_data: 'and some other data.'